version: '2'
services:
  db:
    build: mariadb
  web:
    build: tomcat
    container_name: web
    ports:
     - "8888:8080"
    expose:
     - "8080"
    links:
     - db
  test:
    image: selenium/standalone-firefox-debug:2.53.1
    container_name: selenium_test    
    ports:
     - "5900:5900"
     - "4444:4444"
    volumes:
     - ./test/files:/opt/files
     - ./test/output:/opt/output
    links:
     - web